import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

const categories: Category[] = [
  { id: '1', name: 'Jerseys', slug: 'jerseys' },
  { id: '2', name: 'Accesorios', slug: 'accesorios' },
  { id: '3', name: 'Coleccionables', slug: 'coleccionables' },
  { id: '4', name: 'Boletos', slug: 'boletos' },
];

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || 'https://picsum.photos/seed/placeholder/600/600';

const products: Product[] = [
  {
    id: '1',
    name: 'Jersey Local 2024-25',
    description: 'El jersey oficial del Club León para la temporada 2024-25. Diseñado con tecnología de secado rápido para mantenerte fresco y cómodo. ¡Luce los colores de La Fiera!',
    price: 1699.0,
    images: [findImage('product-jersey-home'), findImage('product-jersey-home'), findImage('product-jersey-home')],
    category: 'Jerseys',
    tags: ['new'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Verde'],
    stock: 150,
  },
  {
    id: '2',
    name: 'Jersey Visitante 2024-25',
    description: 'El elegante jersey de visitante para la temporada 2024-25. Un diseño moderno que puedes usar en el estadio o en la calle.',
    price: 1699.0,
    images: [findImage('product-jersey-away'), findImage('product-jersey-away')],
    category: 'Jerseys',
    tags: ['new'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blanco'],
    stock: 120,
  },
  {
    id: '3',
    name: 'Chamarra de Viaje',
    description: 'La chamarra que usan los jugadores en sus traslados. Cómoda, ligera y con el escudo del equipo bordado.',
    price: 2100.0,
    images: [findImage('product-jacket-travel')],
    category: 'Jerseys',
    tags: [],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 80,
  },
  {
    id: '4',
    name: 'Gorra Escudo Bordado',
    description: 'Gorra clásica de gabardina con el escudo del Club León bordado en alta definición. Ajuste perfecto para cualquier aficionado.',
    price: 499.0,
    images: [findImage('product-cap-logo')],
    category: 'Accesorios',
    tags: [],
    sizes: ['Unitalla'],
    stock: 200,
  },
  {
    id: '5',
    name: 'Bufanda "Dale León"',
    description: 'La bufanda clásica para animar en el Nou Camp. Tejido de alta calidad con los colores tradicionales del equipo.',
    price: 350.0,
    salePrice: 299.0,
    images: [findImage('product-scarf')],
    category: 'Accesorios',
    tags: ['sale'],
    stock: 300,
  },
  {
    id: '6',
    name: 'Balón Oficial #5',
    description: 'Réplica del balón oficial con el que juega el equipo. Ideal para partidos o para tu colección.',
    price: 799.0,
    images: [findImage('product-ball')],
    category: 'Coleccionables',
    tags: [],
    stock: 90,
  },
  {
    id: '7',
    name: 'Playera Dama Escudo',
    description: 'Playera de algodón suave para mujer, con un corte femenino y el escudo del club al frente.',
    price: 550.0,
    images: [findImage('product-tshirt-women')],
    category: 'Jerseys',
    tags: [],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 110,
  },
  {
    id: '8',
    name: 'Sudadera Niño con Capucha',
    description: 'Sudadera cómoda y abrigadora para los pequeños aficionados. Perfecta para los días de partido.',
    price: 899.0,
    images: [findImage('product-hoodie-kids')],
    category: 'Jerseys',
    tags: [],
    sizes: ['4 años', '6 años', '8 años', '10 años'],
    stock: 70,
  },
  {
    id: '9',
    name: 'Taza Escudo Club León',
    description: 'Taza de cerámica para tu café mañanero. Demuestra tu pasión desde primera hora del día.',
    price: 250.0,
    images: [findImage('product-mug')],
    category: 'Coleccionables',
    tags: [],
    stock: 400,
  },
  {
    id: '10',
    name: 'Llavero Metálico Escudo',
    description: 'Llavero de metal de alta calidad con el escudo del equipo. Un accesorio indispensable para todo fan.',
    price: 150.0,
    images: [findImage('product-keychain')],
    category: 'Accesorios',
    tags: [],
    stock: 500,
  },
  {
    id: '11',
    name: 'Jersey Retro 1992',
    description: 'Edición conmemorativa del jersey usado en la temporada del campeonato de 1992. Una joya para coleccionistas.',
    price: 1999.0,
    salePrice: 1599.0,
    images: [findImage('product-jersey-retro')],
    category: 'Jerseys',
    tags: ['sale'],
    sizes: ['M', 'L', 'XL'],
    stock: 50,
  },
  {
    id: '12',
    name: 'Playera de Entrenamiento',
    description: 'La misma playera que usan los jugadores para entrenar. Ligera y transpirable.',
    price: 999.0,
    images: [findImage('product-training-shirt')],
    category: 'Jerseys',
    tags: ['new'],
    sizes: ['S', 'M', 'L'],
    stock: 130,
  },
];

export const getProducts = () => products;
export const getProduct = (id: string) => products.find(p => p.id === id);
export const getCategories = () => categories;
export const getCategory = (slug: string) => categories.find(c => c.slug === slug);
