import type { Metadata } from "next";
import Link from "next/link";
import {
  AVISO_INTRO,
  AVISO_METADATA,
  AVISO_SECTIONS,
  CORREO_PRIVACIDAD,
  DOMICILIO_LEGAL,
  type ContentBlock,
  type InlinePart,
} from "@/content/aviso-privacidad-content";

// Auto-generated by scripts/generate-aviso-content.mjs — do not edit manually.

export const metadata: Metadata = {
  title: AVISO_METADATA.title,
  description: AVISO_METADATA.description,
};

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10 space-y-4">
      <h2 className="text-xl font-semibold">{title}</h2>
      {children}
    </section>
  );
}

function SubSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-3">
      <h3 className="text-lg font-medium">{title}</h3>
      {children}
    </div>
  );
}

function InlineParts({ parts }: { parts: InlinePart[] }) {
  return (
    <>
      {parts.map((part, index) => {
        switch (part.type) {
          case "text":
            return <span key={index}>{part.value}</span>;
          case "strong":
            return <strong key={index}>{part.value}</strong>;
          case "link":
            return (
              <Link
                key={index}
                href={part.href}
                className="text-[#d0ad63] underline underline-offset-2"
              >
                {part.label}
              </Link>
            );
          case "correo":
            return (
              <a
                key={index}
                href={`mailto:${CORREO_PRIVACIDAD}`}
                className="text-[#d0ad63] underline underline-offset-2"
              >
                {CORREO_PRIVACIDAD}
              </a>
            );
          case "domicilio":
            return <span key={index}>{DOMICILIO_LEGAL}</span>;
          default:
            return null;
        }
      })}
    </>
  );
}

function ContentBlocks({ blocks }: { blocks: ContentBlock[] }) {
  return (
    <>
      {blocks.map((block, index) => {
        switch (block.type) {
          case "paragraph":
            return (
              <p
                key={index}
                className="text-muted-foreground leading-7"
              >
                <InlineParts parts={block.parts} />
              </p>
            );
          case "list":
            return (
              <ul
                key={index}
                className="list-disc space-y-2 pl-5 text-muted-foreground"
              >
                {block.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            );
          case "subsection":
            return (
              <SubSection key={index} title={block.title}>
                <ContentBlocks blocks={block.blocks} />
              </SubSection>
            );
          default:
            return null;
        }
      })}
    </>
  );
}

export default function AvisoDePrivacidadPage() {
  return (
    <div className="container max-w-3xl py-10 md:py-16">
      <p className="editorial-label text-[#d0ad63]">{AVISO_METADATA.editorialLabel}</p>
      <h1 className="mt-3 font-headline text-3xl font-semibold uppercase tracking-[0.04em] md:text-4xl">
        {AVISO_METADATA.title}
      </h1>
      <p className="mt-4 text-sm text-muted-foreground">
        Última actualización: {AVISO_METADATA.lastUpdated}
      </p>

      <div className="prose prose-neutral mt-10 max-w-none dark:prose-invert">
        <p className="text-muted-foreground leading-7">{AVISO_INTRO}</p>

        {AVISO_SECTIONS.map((section) => (
          <Section key={section.id} title={section.title}>
            <ContentBlocks blocks={section.blocks} />
          </Section>
        ))}
      </div>
    </div>
  );
}
